import * as esbuild from 'esbuild'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'
import { writeFileSync } from 'fs'

const here = dirname(fileURLToPath(import.meta.url))

// The Scala.js linker output directory. sbt's `cip30Bundle` task sets this
// to `target/scala-X.Y.Z/cardano-prism-cip30-webapp-opt/`. When invoked
// outside sbt, fall back to the conventional path for the current Scala
// version pinned in build.sbt — adjust if you bump the Scala version.
const scalajsDir = process.env.CIP30_SCALAJS_DIR
  ?? resolve(here, 'target/scala-3.3.7/cardano-prism-cip30-webapp-opt')

// Generate a tiny entry that imports from the env-supplied path; esbuild
// inlines it during the bundle pass. This keeps the path resolution purely
// at build time — no filesystem layout assumptions in entry.js.
const entryPath = resolve(here, '.entry.generated.js')
writeFileSync(
  entryPath,
  `// Auto-generated by build.js — do not edit.\n` +
    `import ${JSON.stringify(resolve(scalajsDir, 'cip30webapp.js'))};\n`,
)

// Stub for Node.js built-ins that scalus's NodeJsPlatformSpecific reaches
// for (`fs.writeFileSync`, etc). These code paths exist in the linker output
// but are never executed in the browser — we just need esbuild to resolve
// the require() to *something* so it can finish bundling. The stub throws
// loudly if anything ever does call it.
const stubPath = resolve(here, '.empty-stub.js')
writeFileSync(
  stubPath,
  'const stub = new Proxy(() => { throw new Error("Node built-in called in browser"); }, ' +
    '{ get: () => stub });\n' +
    'export default stub;\n' +
    'export const writeFileSync = stub;\n' +
    'export const appendFileSync = stub;\n' +
    'export const readFileSync = stub;\n' +
    'export const existsSync = stub;\n',
)

await esbuild.build({
  entryPoints: [entryPath],
  bundle: true,
  format: 'esm',
  outfile: 'dist/bundle.js',
  sourcemap: true,
  target: 'es2020',
  logLevel: 'info',
  platform: 'browser',
  // Production minification: matches Scala.js fullLinkJS — tree-shake,
  // mangle names, drop whitespace.
  minify: true,
  // Pin npm resolution here because the Scala.js linker output (in target/)
  // doesn't see this folder via the default upward walk.
  nodePaths: [resolve(here, 'node_modules')],
  alias: {
    fs: stubPath,
    path: stubPath,
    crypto: stubPath,
  },
})
