name: CI

on:
  workflow_dispatch:
    inputs:
      make_snapshot_release:
        description: "Publish libraries's SNAPSHOT"
        default: false
        type: boolean
        required: false
  pull_request:
    branches-ignore:
      - "gh-pages"
  push:
    branches: [master, main]
    tags: ["v*"]

jobs:
  Run-Tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      # https://github.com/japgolly/setup-everything-scala
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for the release tag // `git fetch --tags` will also work
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: adopt@1.11
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or whatever
      - name: Setup Scala.JS
        uses: japgolly/setup-scalajs@v1
      - name: Cache sbt
        uses: coursier/cache-action@v6.3
      ### Compile and TESTS ###
      - run: sbt -mem 2048 -J-Xmx5120m "ciJob"
        env:
          NODE_OPTIONS: "--openssl-legacy-provider" # This is need after node-version "16"

      - name: Release
        if: ((inputs.make_snapshot_release == true) && (github.ref_name == 'master') || startsWith(github.ref, 'refs/tags/v'))
        run: sbt ci-release
        env:
          NODE_OPTIONS: "--openssl-legacy-provider" # This is need after node-version "16"
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          PACKAGES_GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
