# See https://scala-lang.org/blog/2022/07/18/secure-your-dependencies-on-github.html
name: Update Dependency Graph

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17.0
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Setup Scala.js
        uses: japgolly/setup-scalajs@v1
      - name: Cache sbt
        uses: coursier/cache-action@v7
      - name: Install CIP-30 dependencies
        run: npm --prefix cardano-prism-cip30-webapp ci
      - uses: scalacenter/sbt-dependency-submission@v2
        with:
          working-directory: ./
          modules-ignore: root_3
          configs-ignore: test scala-tool scala-doc-tool
