# This workflow will launch at 20:00 every day # https://crontab.guru/#0_10_*_*_*
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

name: Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or whatever
      - name: Setup Scala.JS
        uses: japgolly/setup-scalajs@v1
      - name: Cache sbt
        uses: coursier/cache-action@v6.3
      - name: Install npm dependencies
        run: npm install

      # this ciJobPrepare is to avoid the error java.lang.IllegalArgumentException: requirement failed:
      # You must add typescript as a dependency. /home/runner/scala-steward/workspace/repos/FabioPinheiro/scala-did/node_modules/typescript/lib must exist.
      - run: sbt -mem 2048 -J-Xmx5120m "ciJob"
        env:
          NODE_OPTIONS: "--openssl-legacy-provider" # This is need after node-version "16"

      # ### GPG key for Steward ###
      - name: Import GPG key
        id: import_gpg
        #https://github.com/crazy-max/ghaction-import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        # uses: FabioPinheiro/scala-steward-action@b2d3539f5a99aa69a62581898e187c36fa33b742
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: ${{ steps.import_gpg.outputs.name }}
          sign-commits: true
          signing-key: ${{ secrets.GPG_SIGNING_KEY_ID }}
