# This workflow will launch at 20:00 every day # https://crontab.guru/#0_10_*_*_*
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

name: Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Import GPG key
        id: import_gpg
        #https://github.com/crazy-max/ghaction-import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      - name: Launch Scala Steward
        # uses: scala-steward-org/scala-steward-action@v2
        uses: FabioPinheiro/scala-steward-action@b2d3539f5a99aa69a62581898e187c36fa33b742
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: ${{ steps.import_gpg.outputs.name }}
          sign-commits: true
          signing-key: ${{ secrets.GPG_SIGNING_KEY_ID }}
          max-buffer-size: 25000


# docker pull fthomas/scala-steward
docker run -v /home/fabio/workspace/scala-steward-workspace:/opt/scala-steward -it fthomas/scala-steward:latest \
  -DLOG_LEVEL=TRACE \
  --do-not-fork \
  --workspace  "/opt/scala-steward/workspace" \
  --repos-file "/opt/scala-steward/repos.md" \
  --repo-config "/opt/scala-steward/default.scala-steward.conf" \
  --git-author-email "fabiomgpinheiro@gmail.com" \
  --forge-api-host "https://api.github.com" \
  --forge-login FabioPinheiro \
  --git-ask-pass "/opt/scala-steward/FabioPinheiro.sh" \
  --sign-commits \
  --max-buffer-size 25000
